fn_call_width = 100
fn_single_line = true
group_imports = "StdExternalCrate"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Module"
merge_imports = true
fn_params_layout = "Tall"
fn_args_layout =  "Tall"
